// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js auto-loads .env.local at runtime, but the Prisma CLI doesn't —
// load it explicitly so `prisma migrate`/`db seed` see DATABASE_URL etc.
loadEnv({ path: ".env.local", override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations/seed need a session-level connection (advisory locks,
    // prepared statements) — Supabase's transaction-mode pooler doesn't
    // support that and hangs instead of erroring. DIRECT_URL (session
    // pooler / direct connection) is only set for hosted Supabase; local
    // dev has one plain Postgres and falls back to DATABASE_URL.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
